### ISSUE TITLE
Don't run

### ISSUE THREAD

**Issue by imdp6** [Frizlab/find_unreferenced_xcode_files#1]
![image](https://user-images.githubusercontent.com/28843198/54734564-5f483700-4bdb-11e9-90d6-023c079afa21.png)

**Comment by Frizlab** [comment]
For the time being, the project must be cloned recursively as it has a submodule. You can either use `git clone --recursive URL` for a fresh clone, or `git submodule sync && git submodule update --init --recursive` in the already cloned project.

If you did not setup an SSH key to clone projects through ssh (vs. https), you’ll have to edit the `.gitmodules` file and set the submodule URL to its https counterpart, and then run the submodule sync and update as stated above.
