### ISSUE TITLE
May I ask how is this going?

### ISSUE THREAD

**Issue by imdp6** [Frizlab/find_unreferenced_xcode_files#2]
![image](https://user-images.githubusercontent.com/28843198/54759661-80377900-4c29-11e9-91ff-e637c71c6ebc.png)

**Comment by Frizlab** [comment]
You have to replace `find_unreferenced_xcode_files` with the full path to the compiled binary. Or install the compiled binary in your `PATH`.

**Comment by imdp6** [comment]
I don't know how to use it.

**Comment by imdp6** [comment]
Is there a specific and detailed method of use?

**Comment by Frizlab** [comment]
The command-line you used is actually correct. It does not work because you did not install `find_unreferenced_xcode_files` in your `PATH`. Do you have Homebrew installed? (https://brew.sh) If so, I can give you an easy way to install `find_unreferenced_xcode_files`.

**Comment by Frizlab** [comment]
You can now install the binary with Homebrew with `brew install frizlab/perso/find_unreferenced_xcode_files`.

**Comment by imdp6** [comment]
![image](https://user-images.githubusercontent.com/28843198/54791564-5efc7a00-4c75-11e9-8ce5-507e2a18a46a.png)

**Comment by Frizlab** [comment]
The last command is correct, but you need to specify the path to the `pbxproj` which is inside the `xcodeproj`. In your case this should give `…/CAISHEN.xcodeproj/project.pbxproj`.

Side note, I am aware of some false positive that are detected by my tool. Maybe one day I’ll find the time to remove them and enhance the syntax 🤷‍♂️ There should not be any undetected unreferenced files though.

**Comment by imdp6** [comment]
Thank you very much, the implementation was successful.

**Comment by Frizlab** [comment]
You’re welcome :)
